name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run test
      - run: docker build -t triple-yjs:ci .
